sudo: false
language: python
cache:
  directories:
  - $HOME/.pip-cache/
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
- pip install --cache-dir $HOME/.pip-cache --upgrade pip codecov pytest
- pip install --cache-dir $HOME/.pip-cache --upgrade -r requirements.txt
- python setup.py develop
script:
- pytest
after_success:
- codecov
notifications:
  email: false
